cmake_minimum_required(VERSION 3.19)

set(tsp_known_comps static shared)
set(tsp_comp_static NO)
set(tsp_comp_shared NO)
foreach (tsp_comp IN LISTS ${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS)
    if (tsp_comp IN_LIST tsp_known_comps)
        set(tsp_comp_${tsp_comp} YES)
    else ()
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "tsp does not recognize component `${tsp_comp}`.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
endforeach ()

if (tsp_comp_static AND tsp_comp_shared)
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
        "tsp `static` and `shared` components are mutually exclusive.")
    set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    return()
endif ()

set(tsp_static_targets "${CMAKE_CURRENT_LIST_DIR}/tsp-static-targets.cmake")
set(tsp_shared_targets "${CMAKE_CURRENT_LIST_DIR}/tsp-shared-targets.cmake")

macro(tsp_load_targets type)
    if (NOT EXISTS "${tsp_${type}_targets}")
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "tsp `${type}` libraries were requested but not found.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
    include("${tsp_${type}_targets}")
endmacro()

if (tsp_comp_static)
    tsp_load_targets(static)
elseif (tsp_comp_shared)
    tsp_load_targets(shared)
elseif (DEFINED tsp_SHARED_LIBS AND tsp_SHARED_LIBS)
    tsp_load_targets(shared)
elseif (DEFINED tsp_SHARED_LIBS AND NOT tsp_SHARED_LIBS)
    tsp_load_targets(static)
elseif (BUILD_SHARED_LIBS)
    if (EXISTS "${tsp_shared_targets}")
        tsp_load_targets(shared)
    else ()
        tsp_load_targets(static)
    endif ()
else ()
    if (EXISTS "${tsp_static_targets}")
        tsp_load_targets(static)
    else ()
        tsp_load_targets(shared)
    endif ()
endif ()
